import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const read = (path: string) => readFileSync(resolve(process.cwd(), path), 'utf8');
const rust = read('src-tauri/src/system_node.rs');
const store = read('src/stores/node.ts');
const nodeManager = read('src/views/NodeManager.vue');
const apiTypes = read('src/api/types.ts');
const tauriAdapter = read('src/api/adapters/tauri.ts');
const runner = read('src-tauri/src/runner.rs');

assert.match(rust, /where\.exe/);
assert.match(rust, /pub async fn get_system_node_state\(/);
assert.match(rust, /spawn_blocking\(detect_system_node_state\)/);
assert.match(rust, /fn run_node_version\(executable: &Path\)/);
assert.match(rust, /\.arg\("-v"\)/);
assert.match(rust, /FSCTL_SET_REPARSE_POINT/);
assert.match(rust, /IO_REPARSE_TAG_MOUNT_POINT/);
assert.doesNotMatch(rust, /CreateSymbolicLinkW/);
assert.match(rust, /perform_controller_switch/);
assert.match(rust, /controller_mode/);
assert.match(rust, /target_source == "system"/);
assert.doesNotMatch(rust, /Command::new\(nvm_executable\)/);
assert.doesNotMatch(rust, /args\(\["use", version\]\)/);
assert.doesNotMatch(rust, /Command::new\([^\n]+nvm[^\n]*\)/i);
assert.doesNotMatch(rust, /\.arg\("use"\)/);
assert.match(rust, /ShellExecuteExW/);
assert.match(rust, /"runas"/);
assert.match(rust, /WM_SETTINGCHANGE/);
assert.match(rust, /write_user_path/);
assert.match(rust, /write_machine_path/);
assert.match(rust, /machine_path_conflict/);
assert.match(rust, /find_machine_path_node_before_controller/);
assert.doesNotMatch(rust, /machine_has_controller\.is_some_and\(\|index\| index > 0\)/);
assert.match(rust, /--elevated-node-operation/);

assert.match(store, /systemNodeState/);
assert.match(store, /refreshSystemNode/);
assert.match(store, /switchSystemNode/);
assert.match(store, /systemNodeSwitchSupported/);
assert.match(nodeManager, /systemCurrentNode/);
assert.match(nodeManager, /setSystemNode/);
assert.match(nodeManager, /elevationRequiredMessage/);
assert.doesNotMatch(nodeManager, /chooseSystemRuntimeHint/);
assert.doesNotMatch(nodeManager, /chooseProjectManagerRuntimeHint/);
assert.doesNotMatch(nodeManager, /systemSwitchConfirmTitle/);
assert.doesNotMatch(nodeManager, /pathConflictTitle/);
assert.doesNotMatch(nodeManager, /repairPathPriority/);
assert.match(nodeManager, /group\.effectiveRuntime/);
assert.match(nodeManager, /flex-wrap: nowrap/);
assert.match(nodeManager, /groupCanSetAppDefault/);
assert.match(nodeManager, /groupCanSetSystemNode/);
assert.match(nodeManager, /!group\.isSystemCurrent/);
assert.match(nodeManager, /runtimeDetails/);
assert.match(store, /source !== 'system'/);
assert.match(read('src/components/AddProjectModal.vue'), /selectedExistingRuntime/);

assert.match(apiTypes, /getSystemNodeState\(\): Promise<SystemNodeState>/);
assert.match(apiTypes, /switchSystemNode\(runtime: NodeVersion/);
assert.match(apiTypes, /systemNodeSwitchSupported\(\): Promise<boolean>/);
assert.match(tauriAdapter, /invoke\('get_system_node_state'\)/);
assert.match(tauriAdapter, /invoke\('switch_system_node'/);
assert.match(runner, /system_node::latest_effective_path\(\)/);
assert.match(runner, /"-NoProfile"/);

console.log('systemNodeCenterR22 tests passed');
